### ISSUE TITLE
[mlx][dpdk] net_mlx5: probe of PCI device 0000:af:00.2 aborted after encountering an error: No such file or directory

### ISSUE THREAD

**Issue by zshi-redhat** [intel/sriov-network-device-plugin#123]
The test was to run ``testpmd`` inside pod with two Mellanox ConnectX-4 VFs attached. It failed to probe the allocated devices with below error message:

```
[root@pod-dpdk /]# testpmd -w 0000:af:00.3 -w 0000:af:00.2 -- -i
EAL: Detected 72 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Probing VFIO support...
EAL: PCI device 0000:af:00.2 on NUMA socket 1
EAL:   probe driver: 15b3:1016 net_mlx5
net_mlx5: probe of PCI device 0000:af:00.2 aborted after encountering an error: No such file or directory
EAL: Requested device 0000:af:00.2 cannot be used
EAL: PCI device 0000:af:00.3 on NUMA socket 1
EAL:   probe driver: 15b3:1016 net_mlx5
net_mlx5: probe of PCI device 0000:af:00.3 aborted after encountering an error: No such file or directory
EAL: Requested device 0000:af:00.3 cannot be used
testpmd: No probed ethernet devices
Interactive-mode selected
testpmd: create a new mbuf pool <mbuf_pool_socket_0>: n=715456, size=2176, socket=0
Killed
```

Additional information:

1. Pod spec:
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-dpdk
  annotations:
    k8s.v1.cni.cncf.io/networks: mlx-net, mlx-net
spec:
  containers:
  - name: appcntr3 
    image: zenghui/mlx
    imagePullPolicy: IfNotPresent
    securityContext:
     capabilities:
       add: ["IPC_LOCK"]
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        mellanox.com/sriov: '2' 
        memory: 100Mi
        hugepages-1Gi: 10Gi
        cpu: '8'
      limits:
        mellanox.com/sriov: '2'
        hugepages-1Gi: 10Gi
        cpu: '8'
        memory: 100Mi
    volumeMounts:
    - mountPath: /mnt/huge
      name: hugepage
      readOnly: False
    - mountPath: /var/run
      name: var
      readOnly: False
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
  - name: var
    hostPath:
      path: /var/run/
```

2. device plugin allocated two device successfully:
```
I0424 23:32:20.402636  443962 server.go:114] Allocate() called with &AllocateRequest{ContainerRequests:[&ContainerAllocateRequest{DevicesIDs:[0000:af:00.3 0000:af:00.2],}],}
I0424 23:32:20.402796  443962 pool_stub.go:64] GetDeviceSpecs(): for devices: [0000:af:00.3 0000:af:00.2]
I0424 23:32:20.402823  443962 pool_stub.go:84] GetEnvs(): for devices: [0000:af:00.3 0000:af:00.2]
I0424 23:32:20.402841  443962 pool_stub.go:99] GetMounts(): for devices: [0000:af:00.3 0000:af:00.2]
I0424 23:32:20.402856  443962 server.go:123] AllocateResponse send: &AllocateResponse{ContainerResponses:[&ContainerAllocateResponse{Envs:map[string]string{PCIDEVICE_MELLANOX_COM_SRIOV: 0000:af:00.3,0000:af:00.2,},Mounts:[],Devices:[],Annotations:map[string]string{},}],}
```

3. VF device info:
```
[root@nfvpe-07 deployments]# ethtool -i enp175s0f2 
driver: mlx5_core
version: 5.0-0
firmware-version: 14.24.1000 (MT_2420110034)
expansion-rom-version: 
bus-info: 0000:af:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes
[root@nfvpe-07 deployments]# ethtool -i enp175s0f3
driver: mlx5_core
version: 5.0-0
firmware-version: 14.24.1000 (MT_2420110034)
expansion-rom-version: 
bus-info: 0000:af:00.3
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes
[root@nfvpe-07 deployments]# lspci -v -nn -mm -s 0000:af:00.2
Slot:	af:00.2
Class:	Ethernet controller [0200]
Vendor:	Mellanox Technologies [15b3]
Device:	MT27710 Family [ConnectX-4 Lx Virtual Function] [1016]
SVendor:	Mellanox Technologies [15b3]
SDevice:	Device [0003]
NUMANode:	1

[root@nfvpe-07 deployments]# lspci -v -nn -mm -s 0000:af:00.3
Slot:	af:00.3
Class:	Ethernet controller [0200]
Vendor:	Mellanox Technologies [15b3]
Device:	MT27710 Family [ConnectX-4 Lx Virtual Function] [1016]
SVendor:	Mellanox Technologies [15b3]
SDevice:	Device [0003]
NUMANode:	1

```

4. net-attach-def CRD:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: mlx-net
  annotations:
    k8s.v1.cni.cncf.io/resourceName: mellanox.com/sriov
spec:
  config: '{
  "type": "sriov",
  "name": "sriov-network",
  "ipam": {
    "type": "host-local",
    "subnet": "10.56.217.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "10.56.217.1"
  }
}'
```
@moshe010 @adrianchiris @Mmduh-483 could you please take a look and suggest what config is required to run dpdk?

**Comment by moshe010** [comment]
you need the RDMA patch to run DPDK

**Comment by zshi-redhat** [comment]
> you need the RDMA patch to run DPDK

With rdma patch applied, it went a littler further but hit this error:
```
[root@pod-dpdk /]# testpmd -w 0000:af:00.2 -w 0000:af:00.3 -- -i
EAL: Detected 72 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Probing VFIO support...
EAL: PCI device 0000:af:00.2 on NUMA socket 1
EAL:   probe driver: 15b3:1016 net_mlx5
net_mlx5: MPLS over GRE/UDP tunnel offloading disabled due to old OFED/rdma-core version or firmware configuration
net_mlx5: flow rules relying on switch offloads will not be supported: netlink: failed to remove ingress qdisc: Operation not permitted
EAL: PCI device 0000:af:00.3 on NUMA socket 1
EAL:   probe driver: 15b3:1016 net_mlx5
net_mlx5: MPLS over GRE/UDP tunnel offloading disabled due to old OFED/rdma-core version or firmware configuration
net_mlx5: flow rules relying on switch offloads will not be supported: netlink: failed to remove ingress qdisc: Operation not permitted
Interactive-mode selected
Killed
```

**Comment by pkdas** [comment]
We were able run 100G MLNX ConnectX-5 with DPDK using SRIOVDP and SRIOV. 
The ConnectX-5 NIC needs to be bound to the kernel driver in the POD. And the VFs need to be initialised on the host using mst tool.

https://community.mellanox.com/s/article/howto-configure-sr-iov-for-connectx-4-connectx-5-with-kvm--ethernet-x

**Comment by zshi-redhat** [comment]
> We were able run 100G MLNX ConnectX-5 with DPDK using SRIOVDP and SRIOV.
> The ConnectX-5 NIC needs to be bound to the kernel driver in the POD. And the VFs need to be initialised on the host using mst tool.
> 
> https://community.mellanox.com/s/article/howto-configure-sr-iov-for-connectx-4-connectx-5-with-kvm--ethernet-x

I enabled SR-IOV with mstconfig tool and the interfaces ar bound to kernel driver:

``0000:af:00.0`` is the PCI address of PF on the host:
```
# mstconfig -d 0000:af:00.0 q | grep 'SRIOV\|VFS\|ETH_LINK'
         NUM_OF_VFS                          8               
         SRIOV_EN                            True(1)         
         KEEP_ETH_LINK_UP_P1                 True(1)         
         KEEP_ETH_LINK_UP_P2                 True(1)         
         SRIOV_IB_ROUTING_MODE_P1            True(1)         
         SRIOV_IB_ROUTING_MODE_P2            True(1)
```

Inside pod:
```
[root@pod-dpdk /]# ethtool -i net1
driver: mlx5_core
version: 5.0-0
firmware-version: 14.24.1000 (MT_2420110034)
expansion-rom-version: 
bus-info: 0000:af:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes
[root@pod-dpdk /]# ethtool -i net2
driver: mlx5_core
version: 5.0-0
firmware-version: 14.24.1000 (MT_2420110034)
expansion-rom-version: 
bus-info: 0000:af:00.3
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes
```

**Comment by moshe010** [comment]
@zshi-redhat you need to add the CAP_NET_RAW  to the pod yaml to make it work

**Comment by moshe010** [comment]
or first try it with privileged mode

**Comment by zshi-redhat** [comment]
> or first try it with privileged mode

I can run the privileged pod without problem, but I'd like to see what privileges are required to run the pod in non-privileged mode. Also tried adding both NET_RAW and IPC_LOCK, get below error:
```
EAL: Detected 72 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Probing VFIO support...
EAL: Cannot obtain physical addresses: No such file or directory. Only vfio will function.
error allocating rte services array
EAL: FATAL: rte_service_init() failed
EAL: rte_service_init() failed
PANIC in main():
Cannot init EAL
5: [testpmd() [0x42e637]]
4: [/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f86ce1493d5]]
3: [testpmd(main+0xbd7) [0x42e597]]
2: [/lib64/librte_eal.so.9(__rte_panic+0xbd) [0x7f86cf14a6bd]]
1: [/lib64/librte_eal.so.9(rte_dump_stack+0x2d) [0x7f86cf15603d]]
Aborted (core dumped)
```
what else should I mount into the pod?

**Comment by moshe010** [comment]
@zshi-redhat  can you provide the coredump or run this with gdb and give the backtrace?

**Comment by pkdas** [comment]
need to run as root and DPDK requires rw privilege of sysfs

**Comment by moshe010** [comment]
@zshi-redhat what dpdk version are you using? 
If it the sysfs access issue as @pkdas this should be resolved by [1] 
which means you need dpdk 18.05 and above

[1] - https://github.com/DPDK/dpdk/commit/fc40db997323bb0e9b725a6e8d65eae95372446c

**Comment by zshi-redhat** [comment]
> @zshi-redhat what dpdk version are you using?
> If it the sysfs access issue as @pkdas this should be resolved by [1]
> which means you need dpdk 18.05 and above
> 
> [1] - [DPDK/dpdk@fc40db9](https://github.com/DPDK/dpdk/commit/fc40db997323bb0e9b725a6e8d65eae95372446c)

I'm using dpdk-18.11 packages
```
dpdk-tools-18.11-3.el7_6.x86_64
dpdk-18.11-3.el7_6.x86_64
```
I tried to run as root(0) and mount the ``sys`` path into pod, it didn't solve the problem
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-dpdk
  annotations:
    k8s.v1.cni.cncf.io/networks: mlx-net, mlx-net
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: mlx-dpdk
    image: zenghui/centos-rdma-dpdk
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add: ["IPC_LOCK", "NET_RAW"]
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        mellanox.com/sriov: '2' 
        memory: 100Mi
        hugepages-1Gi: 10Gi
        cpu: '8'
      limits:
        mellanox.com/sriov: '2'
        hugepages-1Gi: 10Gi
        cpu: '8'
        memory: 100Mi
    volumeMounts:
    - mountPath: /mnt/huge
      name: hugepage
      readOnly: False
    - mountPath: /sys
      name: sysfs
      readOnly: False
    - mountPath: /var
      name: var
      readOnly: False
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
  - name: sysfs
    hostPath:
      path: /sys
  - name: var
    hostPath:
      path: /var
```

**Comment by moshe010** [comment]
@zshi-redhat so can you provide the coredump?

**Comment by moshe010** [comment]
@zshi-redhat  can you add also the CAP_NET_ADMIN ?

**Comment by zshi-redhat** [comment]
> @zshi-redhat can you add also the CAP_NET_ADMIN ?

Tried with NET_ADMIN capacity, it went further, but still get 'No such file or directory' error:
```
[root@pod-dpdk /]# testpmd -w 0000:b1:00.2 -w 0000:b1:00.3 -- -i
EAL: Detected 72 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Probing VFIO support...
EAL: PCI device 0000:b1:00.2 on NUMA socket 1
EAL:   probe driver: 15b3:1018 net_mlx5
net_mlx5: probe of PCI device 0000:b1:00.2 aborted after encountering an error: No such file or directory
EAL: Requested device 0000:b1:00.2 cannot be used
EAL: PCI device 0000:b1:00.3 on NUMA socket 1
EAL:   probe driver: 15b3:1018 net_mlx5
net_mlx5: probe of PCI device 0000:b1:00.3 aborted after encountering an error: No such file or directory
EAL: Requested device 0000:b1:00.3 cannot be used
testpmd: No probed ethernet devices
Interactive-mode selected
testpmd: create a new mbuf pool <mbuf_pool_socket_0>: n=715456, size=2176, socket=0
testpmd: preferred mempool ops selected: ring_mp_mc
testpmd: create a new mbuf pool <mbuf_pool_socket_1>: n=715456, size=2176, socket=1
testpmd: preferred mempool ops selected: ring_mp_mc
Done
testpmd>
```

Pod spec:
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-dpdk
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net1, sriov-net1
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: mlx-dpdk
    image: zenghui/centos-rdma-dpdk
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add: ["IPC_LOCK", "NET_RAW", "NET_ADMIN"]
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        mellanox.com/sriov: '2' 
        memory: 100Mi
        hugepages-1Gi: 10Gi
        cpu: '8'
      limits:
        mellanox.com/sriov: '2'
        hugepages-1Gi: 10Gi
        cpu: '8'
        memory: 100Mi
    volumeMounts:
    - mountPath: /mnt/huge
      name: hugepage
      readOnly: False
    - mountPath: /var
      name: var
      readOnly: False
    - mountPath: /sys
      name: sysfs
      readOnly: False
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
  - name: var
    hostPath:
      path: /var
  - name: sysfs
    hostPath:
      path: /sys
```

**Comment by Mmduh-483** [comment]
@zshi-redhat do you have Mellanox OFED installed?

**Comment by Mmduh-483** [comment]
@zshi-redhat can you please try it with this image https://github.com/Amirzei/mlnx_docker_dpdk/blob/master/Dockerfile?

**Comment by moshe010** [comment]
@Mmduh-483, this should work with inbox dpdk. Can you test it without OFED?

**Comment by moshe010** [comment]
@zshi-redhat, why do you mount /sys folder?  can you remove that and try again?

**Comment by moshe010** [comment]
This is the output for us after comment  the /sys/ mount 
declare -x PCIDEVICE_INTEL_COM_SRIOV="0000:02:00.2,0000:02:00.3"
declare -x PWD="/"
declare -x RTE_INCLUDE="/usr/include/dpdk"
declare -x RTE_SDK="/usr/share/dpdk"
declare -x RTE_TARGET="x86_64-default-linuxapp-gcc"
declare -x SHLVL="1"
declare -x TERM="xterm"
declare -x container="docker"
[root@pod-dpdk /]# testpmd -w 0000:02:00.2 -w 0000:02:00.3 -- -i
EAL: Detected 24 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Probing VFIO support...
EAL: PCI device 0000:02:00.2 on NUMA socket 0
EAL:   probe driver: 15b3:1018 net_mlx5
net_mlx5: MPLS over GRE/UDP tunnel offloading disabled due to old OFED/rdma-core version or firmware configuration
EAL: PCI device 0000:02:00.3 on NUMA socket 0
EAL:   probe driver: 15b3:1018 net_mlx5
net_mlx5: MPLS over GRE/UDP tunnel offloading disabled due to old OFED/rdma-core version or firmware configuration
Interactive-mode selected
testpmd: create a new mbuf pool <mbuf_pool_socket_0>: n=331456, size=2176, socket=0
testpmd: preferred mempool ops selected: ring_mp_mc
testpmd: create a new mbuf pool <mbuf_pool_socket_1>: n=331456, size=2176, socket=1
testpmd: preferred mempool ops selected: ring_mp_mc
Configuring Port 0 (socket 0)
Port 0: CA:CB:D6:71:D7:48
Configuring Port 1 (socket 0)
Port 1: 5E:B7:E7:64:22:D1
Checking link statuses...
Done
testpmd> quit

Shutting down port 0...
Stopping ports...
Done
Closing ports...
Done

Shutting down port 1...
Stopping ports...
Done
Closing ports...
Done

Bye...
[root@pod-dpdk /]# rpm -qa | grep dpdk
dpdk-18.11-3.el7_6.x86_64
dpdk-tools-18.11-3.el7_6.x86_64

**Comment by zshi-redhat** [comment]
@moshe010 I got it working by removing the `/sys` mount, Thanks!  do you know the reason why it failed with `/sys` mounted?
btw, did you install `dpdk` and `dpdk-tools` pkgs on the host?
I cannot check the dpdk version by running `rpm -qa | grep dpdk` inside pod unless the dpdk pkgs are installed on the host. And I think we don't need to install dpdk on the host, just in pod would be enough.
Another question, does it work with 2M hugepages? I tried, but it seems not work.

**Comment by moshe010** [comment]
@zshi-redhat, so Mellanox dpdk is Bifurcated Driver [1]  which mean it used the kernel driver so we still need the net device to make it work. (for control). when you mount the /sys we are losing the vf netdevice insead the container. 
I installed the dpdk just in the container. The command I run are inside the container.
Can you send me the error on the 2M hugepages? is it low on Memory?

[1] - https://doc.dpdk.org/guides-18.08/linux_gsg/linux_drivers.html?highlight=bifurcation#bifurcated-driver

**Comment by Mmduh-483** [comment]
@zshi-redhat I tried it with the 2M and it worked fine, can you provide more details about the errors you get

**Comment by zshi-redhat** [comment]
> @zshi-redhat I tried it with the 2M and it worked fine, can you provide more details about the errors you get

pod spec:
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-dpdk
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net1, sriov-net1
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: mlx-dpdk
    image: zenghui/centos-rdma-dpdk
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add: ["IPC_LOCK", "NET_RAW", "NET_ADMIN"]
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        mellanox.com/sriov: '2' 
        memory: 100Mi
        hugepages-2Mi: 10Gi
        cpu: '8'
      limits:
        mellanox.com/sriov: '2'
        hugepages-2Mi: 10Gi
        cpu: '8'
        memory: 100Mi
    volumeMounts:
    - mountPath: /mnt/huge
      name: hugepage
      readOnly: False
    - mountPath: /var
      name: var
      readOnly: False
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
  - name: var
    hostPath:
      path: /var
```
Testpmd log:

```
[root@pod-dpdk /]# testpmd -w 0000:b1:02.5 -w 0000:b1:02.2 -- -i
EAL: Detected 72 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:b1:02.2 on NUMA socket 1
EAL:   probe driver: 15b3:1018 net_mlx5
net_mlx5: MPLS over GRE/UDP tunnel offloading disabled due to old OFED/rdma-core version or firmware configuration
EAL: PCI device 0000:b1:02.5 on NUMA socket 1
EAL:   probe driver: 15b3:1018 net_mlx5
net_mlx5: MPLS over GRE/UDP tunnel offloading disabled due to old OFED/rdma-core version or firmware configuration
Interactive-mode selected
testpmd: create a new mbuf pool <mbuf_pool_socket_0>: n=715456, size=2176, socket=0
testpmd: preferred mempool ops selected: ring_mp_mc
testpmd: create a new mbuf pool <mbuf_pool_socket_1>: n=715456, size=2176, socket=1
testpmd: preferred mempool ops selected: ring_mp_mc
Configuring Port 0 (socket 1)
net_mlx5: port 0 Tx queue 0 CQ creation failure
net_mlx5: port 0 Tx queue allocation failed: Cannot allocate memory
Fail to start port 0
Configuring Port 1 (socket 1)
net_mlx5: port 1 Tx queue 0 CQ creation failure
net_mlx5: port 1 Tx queue allocation failed: Cannot allocate memory
Fail to start port 1
Please stop the ports first
Done
```

**Comment by Mmduh-483** [comment]
>net_mlx5: port 0 Tx queue allocation failed: Cannot allocate memory
@zshi-redhat  It seems it can't reserve huge pages, they may be used, can you please check it

**Comment by zshi-redhat** [comment]
> > net_mlx5: port 0 Tx queue allocation failed: Cannot allocate memory
> > @zshi-redhat  It seems it can't reserve huge pages, they may be used, can you please check it

I tried to remove all the allocated memory and re-run the `testpmd`, the same failure remains.
then I found that kubelet didn't count the 2M hugepage correctly, rebooting solve the problem.

**Comment by zshi-redhat** [comment]
close issue per above comments, free feel to re-open if it happens again.
